package fr.seki.duphunter.gui;

import fr.seki.duphunter.IndexController;
import fr.seki.duphunter.IndexModel;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Sebastien
 */
public class MainFrame extends javax.swing.JFrame {

	public static final String cfgFile = "duplicate.properties";
	private File selectedFile;
	private IndexModel model;
	private IndexController control;

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		model = new IndexModel();
		control = new IndexController(model);
		initComponents();
		indexViewerPanel.setModel(model);
		optionsPanel.setParentFrame(this);
		fileOpenMenuItem.setAction(chooseDBAction);
		fileQuitMenuItem.setAction(quitAction);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
	 * this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        frameContent = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        indexViewerPanel = new fr.seki.duphunter.gui.IndexViewPanel();
        optionsPanel = new fr.seki.duphunter.gui.OptionsPanel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileOpenMenuItem = new javax.swing.JMenuItem();
        fileQuitMenuItem = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();
        helpAboutMenuItem = new javax.swing.JMenuItem();

        fileChooser.setDialogTitle("Selection d'une base");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duplicate Hunter");
        setLocationByPlatform(true);
        setName("MainFrame"); // NOI18N

        tabbedPane.addTab("View Data", indexViewerPanel);
        tabbedPane.addTab("Options", optionsPanel);

        javax.swing.GroupLayout frameContentLayout = new javax.swing.GroupLayout(frameContent);
        frameContent.setLayout(frameContentLayout);
        frameContentLayout.setHorizontalGroup(
            frameContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
        frameContentLayout.setVerticalGroup(
            frameContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuFile.setText("File");

        fileOpenMenuItem.setText("Open...");
        menuFile.add(fileOpenMenuItem);

        fileQuitMenuItem.setText("Quit");
        menuFile.add(fileQuitMenuItem);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");
        menuBar.add(menuEdit);

        menuHelp.setText("Help");

        helpAboutMenuItem.setText("About");
        helpAboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAbout(evt);
            }
        });
        menuHelp.add(helpAboutMenuItem);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAbout
		ImageIcon icn = new ImageIcon(MainFrame.class.getResource("duplicate_search.png"));
		JOptionPane.showMessageDialog(this, "DuplicateHunter", "About this tool", JOptionPane.OK_OPTION, icn);
    }//GEN-LAST:event_displayAbout
	
	private Action chooseDBAction = new AbstractAction("Open...") {
		@Override
		public void actionPerformed(ActionEvent e) {
			String cwd = System.getProperty("user.dir");
			fileChooser.setCurrentDirectory(new File(cwd));
			fileChooser.setFileFilter(new SimpleExtFileFilter("db"));

			int returnVal = fileChooser.showOpenDialog(MainFrame.this);
			if (returnVal == JFileChooser.APPROVE_OPTION) {
				selectedFile = fileChooser.getSelectedFile();
				dbSelectedAction.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, null));
			}
		}
	};
	private Action quitAction = new AbstractAction("Quit") {
		@Override
		public void actionPerformed(ActionEvent e) {
			System.exit(0);
		}
	};
	private Action dbSelectedAction = new AbstractAction() {
		@Override
		public void actionPerformed(ActionEvent e) {
			//JOptionPane.showMessageDialog(MainFrame.this, "You selected " + selectedFile.getPath());
			control.setDB(selectedFile);
			
		}
	};

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			/*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
			*/
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JFileChooser fileChooser;
    javax.swing.JMenuItem fileOpenMenuItem;
    javax.swing.JMenuItem fileQuitMenuItem;
    javax.swing.JPanel frameContent;
    javax.swing.JMenuItem helpAboutMenuItem;
    fr.seki.duphunter.gui.IndexViewPanel indexViewerPanel;
    javax.swing.JMenuBar menuBar;
    javax.swing.JMenu menuEdit;
    javax.swing.JMenu menuFile;
    javax.swing.JMenu menuHelp;
    fr.seki.duphunter.gui.OptionsPanel optionsPanel;
    javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
