/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.seki.duphunter.gui;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.apache.commons.configuration.CompositeConfiguration;
import org.apache.commons.configuration.ConfigurationException;
import org.apache.commons.configuration.PropertiesConfiguration;
import org.apache.commons.configuration.PropertiesConfiguration.PropertiesWriter;
import org.apache.commons.configuration.SystemConfiguration;

/**
 *
 * @author Sebastien
 */
public class OptionsPanel extends javax.swing.JPanel {

	private MainFrame parent = null;
	private PropertiesConfiguration config;
	private DefaultListModel repoModel = new DefaultListModel();

	/**
	 * Creates new form OptionsPanel
	 */
	public OptionsPanel() {
		initComponents();
		repoList.setModel(repoModel);
		retrieveConfig();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
	 * this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        repoList = new javax.swing.JList();
        saveBtn = new javax.swing.JButton();

        repoList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(repoList);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
		try {
			StringBuilder rb = new StringBuilder();
//			String s;
			int i;
//			while(repoModel.elements().hasMoreElements()){
//				if(rb.length() > 0)
//					rb.append(',');
//				s = (String) repoModel.elements().nextElement();
//				rb.append(s);
//			}
			for(i=0 ; i < repoModel.getSize(); i++){
				if(rb.length() > 0)
					rb.append(',');
				rb.append(repoModel.getElementAt(i));
			}
			
			if(config == null){
				config = new PropertiesConfiguration();
				//config.setListDelimiter(',');
				//config.setPath(parent.cfgFile);
			
			}
			config.setProperty("repo", repoModel.elements());

			config.setHeader("Duplicate Hunter configuration file");
			config.save(parent.cfgFile);
		} catch (ConfigurationException ex) {
			Logger.getLogger(OptionsPanel.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_saveBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList repoList;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables

	private void retrieveConfig() {
		File f = new File(parent.cfgFile);
		if (!f.exists()) {
			try {
				f.createNewFile();
			} catch (IOException ex) {
				Logger.getLogger(OptionsPanel.class.getName()).log(Level.SEVERE, null, ex);
			}
			String[] dummy = {"r1", "r2", "r3"};
			for(String r : dummy)
				repoModel.addElement(r);
		} else
		try {
			config = new PropertiesConfiguration();
			config.setListDelimiter(',');
			config.setPath(parent.cfgFile);
			config.load();
			String[] repos = config.getStringArray("repo");
			for (String r : repos) {
				repoModel.addElement(r);
			}
		} catch (ConfigurationException ex) {
			Logger.getLogger(OptionsPanel.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	void setParentFrame(MainFrame parent) {
		this.parent = parent;
	}
}
